### ISSUE TITLE
前置事件监听获取Mapper参数

### ISSUE THREAD

**Issue by balajinima** [noear/wood#4]
要在wood的前置事件中实现一个SQL转换的功能，伪代码如下：

WoodConfig.onExecuteBef((cmd) -> {
           //1.拿到执行时传递的Mapper参数
            Map<String, Object> args=  cmd.getXXX()；
           //2.改写sql
            cmd.text=convert( cmd.text , args)
            return true;
 });

目前无法在前置事件中，拿到Mapper参数用于改写sql， 如  Db.mapper("@batch.get_app_info_by_id", args) 的map，希望作者提供接口

**Comment by noear** [comment]
onExecuteBef 也可以在 DbContext 实例上添加，从而减少范围。（按需选择）

**Comment by noear** [comment]
加好了， cmd.attachment （Map<String,Object> 类型，由 method 的 params 组成）。。。仅 mapper 时，才有值

**Comment by balajinima** [comment]
ok
